### ISSUE TITLE
[typo]namesapce => namespace

### ISSUE THREAD

**Issue by mumutu66** [choerodon/choerodon-cluster-agent#1]
* https://github.com/choerodon/choerodon-cluster-agent/blob/099127a4a88841d93a982fb84ccf844b26baf73d/controller/controller.go#L68 
* https://github.com/choerodon/choerodon-cluster-agent/blob/099127a4a88841d93a982fb84ccf844b26baf73d/controller/namespace/namespace_controller.go#L153
* https://github.com/choerodon/choerodon-cluster-agent/blob/ec037b89e4e4ec62f74e99454da76bf8744affc5/controller/namespace/namespace_controller.go#L80
* https://github.com/choerodon/choerodon-cluster-agent/blob/ec037b89e4e4ec62f74e99454da76bf8744affc5/controller/namespace/namespace_controller.go#L146

**Comment by vinkdong** [comment]
@mumutu66 thanks for the issue, we have fixed it.
